# Generated by Django 4.2.7 on 2023-11-17 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TinhTrang",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Tinhtrang", models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Khachhang",
            fields=[
                (
                    "Cccd",
                    models.CharField(max_length=12, primary_key=True, serialize=False),
                ),
                ("TenKhachHang", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("Sdt", models.CharField(max_length=10, unique=True)),
                ("DiaChi", models.CharField(max_length=120)),
                (
                    "Tinhtrang",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quanlykhachhang.tinhtrang",
                    ),
                ),
            ],
        ),
    ]
