# Generated by Django 4.2.7 on 2023-11-14 18:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quanlynhanvien", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nhanvien",
            name="Cccd",
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name="nhanvien",
            name="Mst",
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name="nhanvien",
            name="Sdt",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
