# Generated by Django 4.2.7 on 2023-11-17 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("quanlykhachhang", "0001_initial"),
        ("quanlynhanvien", "0002_alter_nhanvien_cccd_alter_nhanvien_mst_and_more"),
        ("phieuthuephong", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TinhtrangTT",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Tinhtrang", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Hoadon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Ngaythanhtoan", models.DateField(auto_now_add=True)),
                ("Tienphong", models.IntegerField()),
                (
                    "MaKH",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quanlykhachhang.khachhang",
                    ),
                ),
                (
                    "MaNV",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quanlynhanvien.nhanvien",
                    ),
                ),
                (
                    "MaPT",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="phieuthuephong.phieuthuephong",
                    ),
                ),
                (
                    "Tinhtrang",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quanlytraphong.tinhtrangtt",
                    ),
                ),
            ],
        ),
    ]
