# Generated by Django 4.2.7 on 2023-11-17 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("phieudatphong", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TinhtrangPT",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tinhtrang", models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Phieuthuephong",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Ngayden", models.DateField()),
                ("Ngaydi", models.DateField()),
                (
                    "Maphieudat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="phieudatphong.phieudatphong",
                    ),
                ),
                (
                    "tinhtrangPT",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="phieuthuephong.tinhtrangpt",
                    ),
                ),
            ],
        ),
    ]
