# Generated by Django 4.2.7 on 2023-11-17 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TinhTrangPhong",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Tinhtrang", models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Phong",
            fields=[
                (
                    "Maphong",
                    models.CharField(max_length=5, primary_key=True, serialize=False),
                ),
                ("Loaiphong", models.CharField(max_length=100)),
                ("Giaphong", models.IntegerField()),
                (
                    "Anhphong",
                    models.ImageField(default=None, upload_to="uploads/phong/"),
                ),
                (
                    "Tinhtrangphong",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phong",
                        to="quanlyphong.tinhtrangphong",
                    ),
                ),
            ],
        ),
    ]
