# Generated by Django 4.2.7 on 2023-11-17 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("quanlyphong", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoaiPhong",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Loaiphong", models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name="phong",
            name="Loaiphong",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="quanlyphong.loaiphong"
            ),
        ),
    ]
