# Generated by Django 4.2.7 on 2023-11-17 11:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quanlyphong", "0002_loaiphong_alter_phong_loaiphong"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loaiphong",
            name="Loaiphong",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
