# Generated by Django 4.2.7 on 2023-11-17 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("quanlyphong", "0003_alter_loaiphong_loaiphong"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loaiphong",
            name="Loaiphong",
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name="phong",
            name="Loaiphong",
            field=models.ForeignKey(
                max_length=100,
                on_delete=django.db.models.deletion.CASCADE,
                to="quanlyphong.loaiphong",
            ),
        ),
    ]
