# Generated by Django 4.2.7 on 2023-11-17 18:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quanlyphong", "0005_sogiuong_alter_phong_loaiphong_phong_sogiuong"),
    ]

    operations = [
        migrations.AddField(
            model_name="phong",
            name="describe",
            field=models.TextField(null=True),
        ),
    ]
